version: '3'
services:
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "8888:80"
    volumes:
      - ./app/:/var/www
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: 
      - app
  php:
    build:
      context: ./.docker/php-fpm/.
    volumes:
      - ./app/:/var/www
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks: 
      - app
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3333:3306"
    volumes:
      - app-volume:/var/lib/mysql
    networks: 
      - app
networks:
  app:
    ipam:
       driver: default
       config:
          - subnet: 172.28.0.0/16
volumes:
  app-volume: