version: '3'
services:
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "8888:80"
    volumes:
      - ./src/:/var/www/app
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./.docker/php-fpm/.
    volumes:
      - ./src/:/var/www/app
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3333:3306"
    volumes:
      - app-volume:/var/lib/mysql
volumes:
  app-volume: